swagger: "2.0"
info:
  title: Normacy PDF Pipeline API
  description: |
    API for uploading CTD Module 3 PDFs and supporting documents, and tracking
    their automated curation pipeline (chunking, entity extraction, Neo4j graph export).
  version: "1.0.0"
  contact:
    name: Normacy Engineering

# Injected by Terraform at deploy time — do not edit this file directly.
# Edit api-spec/openapi.yaml.tpl and re-run terraform apply.
x-google-backend:
  address: ${api_function_url}
  protocol: h2

host: "DEPLOYED_GATEWAY_HOSTNAME"
basePath: "/"
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-api-key

security:
  - ApiKeyAuth: []

# ── Paths ─────────────────────────────────────────────────────────────────────

paths:

  /documents/signed-url:
    post:
      operationId: RequestSignedUrl
      summary: Request a signed upload URL
      description: |
        Creates a `document_upload` record and returns a 15-minute signed URL.

        **Upload flow:**
        1. Call this endpoint to get `signedUrl` and `documentUploadId`.
        2. `PUT` the PDF file to `signedUrl` with header `Content-Type: application/pdf`.
        3. The pipeline starts automatically once the file lands in GCS.
        4. Poll `GET /documents/{documentUploadId}/job` to track progress.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/SignedUrlRequest"
      responses:
        "201":
          description: Signed URL created successfully
          schema:
            $ref: "#/definitions/SignedUrlResponse"
        "400":
          description: Validation error
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"

  /documents:
    get:
      operationId: ListDocuments
      summary: List document uploads
      description: Returns all document uploads for the account, newest first.
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
          minimum: 1
        - name: limit
          in: query
          type: integer
          default: 50
          minimum: 1
          maximum: 100
      responses:
        "200":
          description: Paginated list of document uploads
          schema:
            $ref: "#/definitions/DocumentListResponse"

  /documents/{documentId}/job:
    get:
      operationId: GetDocumentJob
      summary: Get the latest processing job for a document
      description: |
        Returns the most recent `processing_job` for a document.
        Poll this endpoint after upload to track pipeline progress.
        When `status` is `completed`, the curated files are available in GCS
        at the path returned in `outputGcsPath`.
      parameters:
        - name: documentId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: Processing job
          schema:
            $ref: "#/definitions/JobResponse"
        "404":
          description: No job found for this document
          schema:
            $ref: "#/definitions/Error"

  /jobs/{jobId}:
    get:
      operationId: GetJob
      summary: Get a processing job by ID
      parameters:
        - name: jobId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: Processing job
          schema:
            $ref: "#/definitions/JobResponse"
        "404":
          description: Job not found
          schema:
            $ref: "#/definitions/Error"

# ── Definitions ───────────────────────────────────────────────────────────────

definitions:

  SignedUrlRequest:
    type: object
    required:
      - fileName
      - contentType
      - documentType
    properties:
      fileName:
        type: string
        description: Original file name including .pdf extension
        example: "module3-ibuprofen-batch2024.pdf"
      contentType:
        type: string
        description: Must be application/pdf
        enum: ["application/pdf"]
      documentType:
        type: string
        description: Whether this is a primary CTD Module 3 or a supporting evidence document
        enum: ["ctd_module3", "supporting"]
      ctdSection:
        type: string
        description: |
          Required when documentType is "supporting".
          The CTD section this document provides evidence for.
        example: "3.2.S.4.1"

  SignedUrlResponse:
    type: object
    properties:
      signedUrl:
        type: string
        description: |
          PUT your PDF to this URL with header Content-Type: application/pdf.
          Valid for 15 minutes.
      gcsPath:
        type: string
        description: GCS object path where the file will be stored
        example: "uploads/abc123/module3-ibuprofen.pdf"
      documentUploadId:
        type: string
        format: uuid
        description: Use this ID to poll /documents/{id}/job

  DocumentUpload:
    type: object
    properties:
      id:
        type: string
        format: uuid
      accountId:
        type: string
      fileName:
        type: string
      gcsPath:
        type: string
      documentType:
        type: string
        enum: ["ctd_module3", "supporting"]
      ctdSection:
        type: string
        description: Present only for supporting documents
        x-nullable: true
      status:
        type: string
        enum: ["uploaded", "processing", "curated", "failed"]
        description: |
          - uploaded: file received, pipeline not yet started
          - processing: pipeline is running
          - curated: pipeline completed successfully
          - failed: pipeline failed (check the job for errorMessage)
      uploadedAt:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time

  DocumentListResponse:
    type: object
    properties:
      documents:
        type: array
        items:
          $ref: "#/definitions/DocumentUpload"
      page:
        type: integer
      limit:
        type: integer

  ProcessingJob:
    type: object
    properties:
      id:
        type: string
        format: uuid
      documentUploadId:
        type: string
        format: uuid
      status:
        type: string
        enum: ["pending", "running", "completed", "failed"]
      errorMessage:
        type: string
        x-nullable: true
        description: Present only when status is "failed"
      chunksCount:
        type: integer
        x-nullable: true
        description: Number of chunks extracted. Present when status is "completed".
      entitiesCount:
        type: integer
        x-nullable: true
        description: Number of entities extracted. Present when status is "completed".
      outputGcsPath:
        type: string
        x-nullable: true
        description: |
          GCS prefix of the curated output files. Present when status is "completed".
          Files available under this prefix:
            - chunks.csv
            - entities.csv
            - relationships.csv
            - graph.cypher  (Neo4j import script)
            - tables/*.csv  (extracted tables)
      startedAt:
        type: string
        format: date-time
        x-nullable: true
      completedAt:
        type: string
        format: date-time
        x-nullable: true

  JobResponse:
    type: object
    properties:
      job:
        $ref: "#/definitions/ProcessingJob"

  Error:
    type: object
    properties:
      error:
        type: string
        description: Human-readable error message
      code:
        type: string
        description: Machine-readable error code in SCREAMING_SNAKE_CASE
        example: "MISSING_CTD_SECTION"
      statusCode:
        type: integer
        example: 400
